### ISSUE TITLE
Feature - Select which feature to disable.

### ISSUE THREAD

**Issue by botmaster** [vinkla/headache#16]
Hello,
Thanks for this great plugin. 
I would like to select which feature to disable. Is it possible ?

Thanks.

**Comment by vinkla** [comment]
Hello Pascal, I'm glad you like the plugin. Currently, there are no settings to enable or disable filters. This plugin is designed to be plug-n-play and comes with sensible defaults. Could you please let me know which feature(s) you would like to disable in the plugin and provide the reason behind it?

**Comment by botmaster** [comment]
I was just curious to know if it was possible ^^.
It would be nice if I could enable Gutenberg styles. I'm going to spend a lot of time recreating a part of them.

PS: I'm a beginner in wordpress development.

**Comment by vinkla** [comment]
Yes, it should be possible to [remove the action](Yes, it should be possible to remove the action by using the `remove_action` function.) by using the `remove_action` function.
